theme: 
  - osuny
  - osuny-masonry
enableRobotsTXT: true
removePathAccents: true
pagination:
  pagerSize: 30
params:
  debug:
    productionUrl: "https://www.diapason-agence.fr"
  default:
    index:
      taxonomies:
        display: true
        layout: inline
        show_name: false
  summary:
    position: hero
  search:
    active: false
  logo:
    header: ''
    footer: ''
  toc:
    disabled: true
  posts:
    index:
      options:
        image: false
        categories: false
    single:
      taxonomies:
        position: hero
        show_name: false
      summary:
        position: content # hero | content
  projects:
    index:
      options:
        summary: false
        year: true
    single:
      taxonomies:
        position: hero
        show_name: false
      summary:
        position: content
    share_links:
      enabled: false
  home:
    head:
      title: site
  image_sizes:
    sections:
      projects:
        layouts:
          grid:
            mobile:   360
            tablet:   555
            desktop:  575